"""Added initial table

Revision ID: 677a48982ffc
Revises: 
Create Date: 2023-03-25 17:14:18.965679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677a48982ffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_data',
    sa.Column('game_data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=90), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('game_data_id'),
    sa.UniqueConstraint('answer'),
    sa.UniqueConstraint('question')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_winner', sa.BOOLEAN(), nullable=True),
    sa.Column('in_game', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('username', sa.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('vk_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_data_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_data_id'], ['game_data.game_data_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('player_game_data',
    sa.Column('player_game_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_data')
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('player')
    op.drop_table('game_data')
    # ### end Alembic commands ###
