"""Added initial table

Revision ID: 8a61927d8c2a
Revises: 
Create Date: 2023-04-01 15:23:09.341898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a61927d8c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(length=300), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('username', sa.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=60), nullable=False),
    sa.Column('password', sa.VARCHAR(length=75), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_data_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('chat_id', sa.VARCHAR(length=15), nullable=False),
    sa.Column('chat_message_id', sa.Integer(), nullable=True),
    sa.Column('guessed_word', sa.VARCHAR(length=30), nullable=False),
    sa.Column('required_player_count', sa.SmallInteger(), nullable=False),
    sa.Column('previous_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_data_id'], ['game_data.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_player_id'], ['player.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_winner', sa.BOOLEAN(), nullable=False),
    sa.Column('in_game', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('game')
    op.drop_table('admin')
    op.drop_table('user')
    op.drop_table('game_data')
    # ### end Alembic commands ###
