"""Added initial table

Revision ID: bc12b49f4f96
Revises: 
Create Date: 2023-03-28 22:00:26.627950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc12b49f4f96"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_data",
        sa.Column(
            "game_data_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("question", sa.VARCHAR(length=90), nullable=False),
        sa.Column("answer", sa.VARCHAR(length=30), nullable=False),
        sa.PrimaryKeyConstraint("game_data_id"),
        sa.UniqueConstraint("answer"),
        sa.UniqueConstraint("question"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vk_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=45), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=45), nullable=False),
        sa.Column("username", sa.VARCHAR(length=45), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("vk_id"),
    )
    op.create_table(
        "admin",
        sa.Column("admin_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.VARCHAR(length=60), nullable=False),
        sa.Column("password", sa.VARCHAR(length=75), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.user_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("admin_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "game",
        sa.Column("game_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_data_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("required_player_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_data_id"], ["game_data.game_data_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_table(
        "player",
        sa.Column(
            "player_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("is_winner", sa.BOOLEAN(), nullable=True),
        sa.Column("in_game", sa.BOOLEAN(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    op.create_table(
        "player_game_data",
        sa.Column(
            "player_game_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["game.game_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["player.player_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("player_game_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_game_data")
    op.drop_table("player")
    op.drop_table("game")
    op.drop_table("admin")
    op.drop_table("user")
    op.drop_table("game_data")
    # ### end Alembic commands ###
