name: Check project
on: [push]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          python-version: 3.10.7.final.0
          black_args: ". --check"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: update pythonpath
        run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/kts-project/kts-project" >> $GITHUB_ENV

      - name: set CONFIGPATH
        run: echo "CONFIGPATH=/home/runner/work/kts-project/kts-project/tests/config.yml" >> $GITHUB_ENV

      - name: handle migrations
        run: alembic upgrade head
          
